config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create]
    resources :likes, only: [:create]
  end
  post '/users/:user_id/posts/:id' , to: 'comments#create'
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_save :comment_counter

  def comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id', class_name: 'Post'
  after_save :like_counter

  def like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy

  after_initialize :init

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def init
    self.comments_counter ||= 0 # will set the default value only if it's nil
    self.likes_counter ||= 0 # will set the default value only if it's nil
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def self.recent_comments(post)
    post.comments.order(id: :desc).limit(5).eager_load(:author)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  after_initialize :init

  validates :name, presence: true, length: { minimum: 3 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.recent_posts
    Post.order(id: :desc).limit(3)
  end

  def self.all_posts(user)
    Post.where('author_id = ?', user.id).order(id: :desc)
  end

  def init
    self.posts_counter ||= 0 # will set the default value only if it's nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:id])
    @comment = Comment.new(comment_params)
    @comment.author_id = find_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to user_post_path(find_user.id, @post.id)
    else
      redirect_to user_post_path(find_user.id, @post.id), alert: 'Comments not created!'
    end
  end

  def find_user
    User.find(params[:user_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = Like.new
    @like.post_id = @post.id
    @like.author_id = find_user.id

    flash[:notice] = 'Liked it!' if @like.save
    redirect_to user_post_path(find_user.id, @post.id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_user
    User.find(params[:user_id])
  end

  private

  def like_params
    params.require(:like).permit(:post_id, :author_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @posts = Post.last(3)
  end

  def show
    @post = current_user.posts.find(params[:id])
    @user = current_user
    @comments = @post.comments
    @liked_post = Post.find(params[:id]).id
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_posts_path(current_user.id)
    else
      redirect_to user_post_path(current_user.id), alert: 'Post not created!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
    <% end %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/single_user' %>
<%= render 'shared/link_to_post_create' %>
<%= render 'shared/posts_with_comments' %>

<%= button_to 'pagination' %>

app/views/posts/new.html.erb
<%= form_with url: user_posts_path, model: @post, local: true do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit "Create post" %><br>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render 'shared/single_post' %>
<%= render 'shared/single_post_comment' %>
<%= render 'shared/link_to_post_create' %>

<%= render 'shared/form_comment' %>

app/views/shared/_form_comment.html.erb
<%=  form_with url: user_post_path, model:[ @post,  @post.comments.build ], method: 'post' do |f| %>
  <div>
    <%= f.label 'Comment to this post:' %><br>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit "Create comment" %><br>
  </div>
<% end %>

app/views/shared/_form_like.html.erb
<%=  form_with  model:[ @post,  @user ], method: 'post' do |f| %>
  <div>
    <%= f.submit "Like" %><br>
  </div>
<% end %>

app/views/shared/_link_to_post_create.html.erb
<h3><%= link_to 'Click to Create Post', new_user_post_path, class: 'link' %></h3>

app/views/shared/_log_out.html.erb
<%= button_to "logout", destroy_user_session_path, method: :delete %>

app/views/shared/_posts_with_comments.html.erb
<% User.all_posts(@user).each do |p| %>
  <div class='user-posts frame'>
   <p class='post-title'><%= link_to p.title, user_post_path(@user.id ,p.id) %></p>
   <p class='post-text'><%= p.text%></p>
   <h5></h5>
   <div class='post-counters'>
     <p class='post-c-counter'>Comments: <%= p.comments_counter %></p>
     <p class='post-l-counter'>Likes: <%= p.likes_counter %></p>
   </div>
  </div>

<% if p.comments_counter > 0 %>
  <div class='comment-container frame'>
  <% Post.recent_comments(p).each do |c| %>
     <div class='comments'>
      <p>Username: <%= c.author.name %></p>
      <p>Comment: <%= c.text %></p>
    </div>
  <% end %>
  </div>
  
  <%else%>
  <p class="no_comment frame">No comments yet</p>

<% end %>

<% end %>

app/views/shared/_recent_posts.html.erb
<% User.recent_posts.each do |p| %>
  <div class='user-posts frame'>
   <p class='post-title'><%= link_to p.title, user_posts_path(current_user.id) %></p>
   <p class='post-text'><%= p.text%></p>

   <div class='post-counters'>
     <p class='post-c-counter'>Comments: <%= p.comments_counter %></p>
     <p class='post-l-counter'>Likes: <%= p.likes_counter %></p>
   </div>
  </div>
  <% end %>
 

 

app/views/shared/_single_post.html.erb
<div class='user-post frame'>
  <div class='post-head'>
     <p class='post-title'><%= @post.title %> by <%= @post.author.name %></p>
  </div>

    <div class='post-counters'>
     <p class='post-c-counter'>Comments: <%= @post.comments_counter %></p>
     <p class='post-l-counter'>Likes: <%= @post.likes_counter %></p>
   </div>
  </div>

  <p class='post-text'><%= @post.text %></p>
  <%= button_to 'Like', user_likes_path(post_id: @liked_post), action: 'create', form_class: "like" %>
</div>

app/views/shared/_single_post_comment.html.erb
<% if @post.comments_counter > 0 %>
  <div class='comment-container frame'>
  <% Post.recent_comments(@post).each do |c| %>
     <div class='comments'>
      <p>Username: <%= c.author.name %></p>
      <p>Comment: <%= c.text %></p>
    </div>
  <% end %>
  </div>
  
  <%else%>
  <p class="no_comment frame">No comments yet</p>

<% end %>

app/views/shared/_single_user.html.erb
<div class='container-user-post'>
    <%= image_tag current_user.photo %>
    <div class='user-content frame'>
      <h1><%= current_user.name %></h1>
      <h3 class='post-counter'>Number of posts:<%= current_user.posts_counter %></h3>
      <%= render 'shared/log_out' %>
    </div>
    
</div>

app/views/shared/_user_posts.html.erb
<% @user.posts.all.each do |p| %>
  <div class='user-posts frame'>
   <p class='post-title'><%= p.title %></p>
   <p class='post-text'><%= p.text%></p>
   <div class='post-counters'>
     <p class='post-c-counter'>Comments: <%= p.comments_counter %></p>
     <p class='post-l-counter'>Likes: <%= p.likes_counter %></p>
   </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class='container-users'>
    <%= image_tag user.photo %>
    <div class='user-content frame'>
      <h1><%= link_to user.name, user_path(user.id), class: 'link' %></h1>
      <h3 class='post-counter'>Number of posts:<%= user.posts_counter %></h3>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/single_user' %>

<div class='bio frame'>
  <h2>Bio</h2>
  <p><%= current_user.bio %></p>
</div>


  <%= render 'shared/recent_posts' %>
 
  <button>
  <%= link_to 'See all posts', user_posts_path(current_user.id) %>
  </button>
  
  
 
 

  



  